version: '3.8'

services:
  sepsis_clinical:
    build: ./docker
    image: sepsis_clinical_env:latest
    container_name: sepsis_clinical_dev
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - JUPYTER_TOKEN=biotech
    shm_size: '8gb'